/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedViolationsRouteImport } from './routes/_authenticated/violations'
import { Route as AuthenticatedViolationTypesRouteImport } from './routes/_authenticated/violation-types'
import { Route as AuthenticatedSectionViolationsRouteImport } from './routes/_authenticated/section-violations'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedNewViolationRouteImport } from './routes/_authenticated/new-violation'
import { Route as AuthenticatedEmployeesRouteImport } from './routes/_authenticated/employees'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedArchiveRouteImport } from './routes/_authenticated/archive'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedViolationsRoute = AuthenticatedViolationsRouteImport.update({
  id: '/violations',
  path: '/violations',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedViolationTypesRoute =
  AuthenticatedViolationTypesRouteImport.update({
    id: '/violation-types',
    path: '/violation-types',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSectionViolationsRoute =
  AuthenticatedSectionViolationsRouteImport.update({
    id: '/section-violations',
    path: '/section-violations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewViolationRoute =
  AuthenticatedNewViolationRouteImport.update({
    id: '/new-violation',
    path: '/new-violation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployeesRoute = AuthenticatedEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArchiveRoute = AuthenticatedArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/archive': typeof AuthenticatedArchiveRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/new-violation': typeof AuthenticatedNewViolationRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/section-violations': typeof AuthenticatedSectionViolationsRoute
  '/violation-types': typeof AuthenticatedViolationTypesRoute
  '/violations': typeof AuthenticatedViolationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/archive': typeof AuthenticatedArchiveRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/new-violation': typeof AuthenticatedNewViolationRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/section-violations': typeof AuthenticatedSectionViolationsRoute
  '/violation-types': typeof AuthenticatedViolationTypesRoute
  '/violations': typeof AuthenticatedViolationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/archive': typeof AuthenticatedArchiveRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/employees': typeof AuthenticatedEmployeesRoute
  '/_authenticated/new-violation': typeof AuthenticatedNewViolationRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/section-violations': typeof AuthenticatedSectionViolationsRoute
  '/_authenticated/violation-types': typeof AuthenticatedViolationTypesRoute
  '/_authenticated/violations': typeof AuthenticatedViolationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/archive'
    | '/dashboard'
    | '/employees'
    | '/new-violation'
    | '/reports'
    | '/section-violations'
    | '/violation-types'
    | '/violations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/archive'
    | '/dashboard'
    | '/employees'
    | '/new-violation'
    | '/reports'
    | '/section-violations'
    | '/violation-types'
    | '/violations'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/archive'
    | '/_authenticated/dashboard'
    | '/_authenticated/employees'
    | '/_authenticated/new-violation'
    | '/_authenticated/reports'
    | '/_authenticated/section-violations'
    | '/_authenticated/violation-types'
    | '/_authenticated/violations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/violations': {
      id: '/_authenticated/violations'
      path: '/violations'
      fullPath: '/violations'
      preLoaderRoute: typeof AuthenticatedViolationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/violation-types': {
      id: '/_authenticated/violation-types'
      path: '/violation-types'
      fullPath: '/violation-types'
      preLoaderRoute: typeof AuthenticatedViolationTypesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/section-violations': {
      id: '/_authenticated/section-violations'
      path: '/section-violations'
      fullPath: '/section-violations'
      preLoaderRoute: typeof AuthenticatedSectionViolationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/new-violation': {
      id: '/_authenticated/new-violation'
      path: '/new-violation'
      fullPath: '/new-violation'
      preLoaderRoute: typeof AuthenticatedNewViolationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employees': {
      id: '/_authenticated/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AuthenticatedEmployeesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/archive': {
      id: '/_authenticated/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof AuthenticatedArchiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedArchiveRoute: typeof AuthenticatedArchiveRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmployeesRoute: typeof AuthenticatedEmployeesRoute
  AuthenticatedNewViolationRoute: typeof AuthenticatedNewViolationRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSectionViolationsRoute: typeof AuthenticatedSectionViolationsRoute
  AuthenticatedViolationTypesRoute: typeof AuthenticatedViolationTypesRoute
  AuthenticatedViolationsRoute: typeof AuthenticatedViolationsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedArchiveRoute: AuthenticatedArchiveRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmployeesRoute: AuthenticatedEmployeesRoute,
  AuthenticatedNewViolationRoute: AuthenticatedNewViolationRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSectionViolationsRoute: AuthenticatedSectionViolationsRoute,
  AuthenticatedViolationTypesRoute: AuthenticatedViolationTypesRoute,
  AuthenticatedViolationsRoute: AuthenticatedViolationsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
